dnd_classes = [
    "Artificer",
    "Barbarian",
    "Bard",
    "Blood Hunter",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard"
]
dnd_subclasses = [
    ["Alchemist", "Armorer", "Artillerist", "Battle Smith"],
    ["Path of the Ancestral Guardian", "Path of the Battlerager", "Path of the Beast", "Path of the Berserker", "Path of the Giant", "Path of the Storm Herald", "Path of the Totem Warrior", "Path of the Zealot", "Path of Wild Magic"],
    ["College of Creation", "College of Eloquence", "College of Glamour", "College of Lore", "College of Spirits", "College of Swords", "College of the Road", "College of Valor", "College of Whispers"],
    ["Order of the Ghostslayer", "Order of the Lycan", "Order of the Mutant", "Order of the Profane Soul"],
    ["Arcana Domain", "Community Domain", "Death Domain", "Forge Domain", "Grave Domain", "Knowledge Domain", "Life Domain", "Light Domain", "Nature Domain", "Night Domain", "Order Domain", "Peace Domain", "Tempest Domain", "Trickery Domain", "Twighlight Domain", "War Domain"],
    ["Circle of Dreams", "Circle of Spores", "Circle of Stars", "Circle of the Land", "Circle of the Moon", "Circle of the Shepherd", "Circle of Wildfire"],
    ["Arcane Archer", "Battle Master", "Cavalier", "Champion", "Echo Knight", "Eldritch Knight", "Gunslinger", "Psi Warrior", "Purple Dragon Knight", "Rune Knight", "Samurai", "Scofflaw"],
    ["Way of the Ascendant Dragon", "Way of the Astral Self", "Way of the Cobolt Soul", "Way of the Drunken Master", "Way of the Four Elements", "Way of the Kensei", "Way of the Long Death", "Way of Mercy", "Way of the Open Hand", "Way of Shadow", "Way of the Sun Soul"],
    ["Oathbreaker", "Oath of Conquest", "Oath of Devotion", "Oath of Glory", "Oath of Redemption", "Oath of the Ancients", "Oath of the Crown", "Oath of the Open Sea", "Oath of Vengeance", "Oath of the Watchers"],
    ["Beast Master", "Drakewarden", "Fey Wanderer", "Gloom Stalker", "Horizon Walker", "Hunter", "Monster Slayer", "Swarmkeeper"],
    ["Arcane Trickster", "Assassin", "Inquisitive", "Mastermind", "Phantom", "Scout", "Soulknife", "Swashbuckler", "Thief"],
    ["Aberrant Mind", "Clockwork Soul", "Divine Soul", "Draconic Bloodline", "Lunar Sorcery", "Shadow Magic", "Storm Sorcery", "Wild Magic"],
    ["The Archfey", "The Celestial", "The Fathomless", "The Fiend", "The Genie", "The Great Old One", "The Hexblade", "The Undead", "The Undying"],
    ["Bladesinging", "Chronurgy Magic", "Graviturgy Magic", "Order of Scribes", "School of Abjuration", "School of Conjuration", "School of Divination", "School of Enchantment", "School of Evocation", "School of Illusion", "School of Necromancy", "School of Transmutation", "War Magic"],
]
dnd_races = [
    "Arakocra",
    "Aasimar",
    "Air Genasi",
    "Astral Elf",
    "Autognome",
    "Bearfolk",
    "Bugbear",
    "Centaur",
    "Cervan",
    "Corvum",
    "Changeling",
    "Darakhul",
    "Deep Gnome",
    "Dragonborn",
    "Duergar",
    "Dwarf",
    "Earth Genasi",
    "Eladrin",
    "Elf",
    "Erina",
    "Fairy",
    "Firbolg",
    "Fire Genasi",
    "Gallus",
    "Giff",
    "Githyanki",
    "Githzerai",
    "Goblin",
    "Goliath",
    "Gnome",
    "Grung",
    "Hadozee",
    "Half-elf",
    "Halfling",
    "Half-orc",
    "Harengon",
    "Hedge",
    "Hobgoblin",
    "Human",
    "Jerbeen",
    "Kalashtar",
    "Kender",
    "Kenku",
    "Kobold",
    "Leonin",
    "Lizardfolk",
    "Locathah",
    "Loxodon",
    "Luma",
    "Mapach",
    "Minotaur",
    "Orc",
    "Owlin",
    "Plasmoid",
    "Quickstep",
    "Raptor",
    "Ratatosk",
    "Ravenfolk",
    "Satarre",
    "Satyr",
    "Sea Elf",
    "Shadar-kai",
    "Shade",
    "Shadow Goblin",
    "Shifter",
    "Simic Hybrid",
    "Strig",
    "Tabaxi",
    "The Disembodied",
    "Thri-kreen",
    "Tiefling",
    "Tortle",
    "Triton",
    "Umbral Human",
    "Vedalken",
    "Verdan",
    "Vulpin",
    "Warforged",
    "Water Genasi",
    "Wechselkind",
    "Yuan-ti"
]